// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atyznzkdlepxtjsvnjwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0eXpuemtkbGVweHRqc3ZuandqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDU3NjEsImV4cCI6MjA2MzY4MTc2MX0.mRDfAdt_HYm9eorEbL4zXCVzdutsfEUwZbSYnOM9iYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);